run_config:
    driver_type: chrome
    url: http://192.168.3.1
    rerun: 1
    max_fail: 5

web_login:
    password: 12345678


my_wifi:
    ssid2g: hilink-test-master
    ssid5g: hilink-test-master-5G
    passwd2g: 012345678901234567890123456789012345678901234567890123456789012
    passwd5g: 012345678901234567890123456789012345678901234567890123456789012


telnet_login:
    username: xxx
    password: xxx
    host: xxx
    port: xxx

ssh2_login:
    username: xxx
    password: xxx
    host: xxx
    port: xxx


app_desired_caps:
    platformName : Android
    platformVersion : 7.1.1
    deviceName : emulator-5554
    appPackage : com.utt.smart
    appActivity : xxx

#mysql_config:
#    host: 127.0.0.1
#    port: 3306
#    user: root
#    password: password
#    db_name: pythontest

#log:
#    file_name: test.log
#    backup: 5
#    console_level: WARNING
#    file_level: DEBUG
#    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
assertion:
    browser_title: 华为路由WS5200 增强版




